name: Build and Release

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install all dependencies (including dev)
        run: npm install   # 或 npm ci（如果项目有 package-lock.json）

      - name: Type check & Build
        run: |
          npm run check
          npm run build

      - name: Read release notes
        id: release_note
        run: |
          echo 'body<<EOF' >> $GITHUB_OUTPUT
          cat RELEASE.md >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Create Release and Upload Assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}
          overwrite: true
          file_glob: true
          body: ${{ steps.release_note.outputs.body }}
